### ISSUE TITLE
AttributeError: 'UserInterface' object has no attribute 'current_timeframe'      

### ISSUE THREAD

**Issue by qtbgo** [Skinok/backtrader-pyqt-ui#4]
when I run main.py, error occurs:
(venv_quant389) E:\myquant\backtrader-pyqt-ui-main>e:/myquant/venv_quant389/Scripts/python.exe e:/myquant/backtrader-pyqt-ui-main/main.py
Traceback (most recent call last):
  File "e:\myquant\backtrader-pyqt-ui-main\strategyTesterUI.py", line 46, in strategyNameActivated
    self.controller.addStrategy(stratBaseName)
  File "e:\myquant\backtrader-pyqt-ui-main\SkinokBacktraderUI.py", line 212, in addStrategy
    mod = __import__(strategyName, fromlist=[strategyName]) # first strategyName is the file name, and second (fromlist) is the class name
  File "E:\myquant\backtrader-pyqt-ui-main/strategies\AiStableBaselinesModel.py", line 23, in <module>
    from stable_baselines3 import PPO
ModuleNotFoundError: No module named 'stable_baselines3'
Traceback (most recent call last):
  File "e:\myquant\backtrader-pyqt-ui-main\userInterface.py", line 645, in resetChart
    self.fpltWindow[self.current_timeframe].resetChart()
AttributeError: 'UserInterface' object has no attribute 'current_timeframe'
Traceback (most recent call last):
  File "e:\myquant\backtrader-pyqt-ui-main\userInterface.py", line 665, in addSma
    self.fpltWindow[self.current_timeframe].drawSma( period, qColor, width)      
AttributeError: 'UserInterface' object has no attribute 'current_timeframe'

**Comment by qtbgo** [comment]
solved
